services:
  backend:
    build: ./backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend/badminton-app
    ports:
      - "3000:80"
    depends_on:
      - backend