services:
  backend:
    build: ./backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres.lbmpbkhjcouijtumynxm:#gns*t5szBun3JN@aws-0-ca-central-1.pooler.supabase.com:6543/postgres
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend/badminton-app
    ports:
      - "3000:80"
    depends_on:
      - backend
