"""Add foreign key constraints with cascade

Revision ID: bb7199ca1f21
Revises: 
Create Date: 2024-07-09 16:06:36.802294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7199ca1f21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('losers_user_id_fkey', 'losers', type_='foreignkey')
    op.drop_constraint('losers_match_id_fkey', 'losers', type_='foreignkey')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint('winners_user_id_fkey', 'winners', type_='foreignkey')
    op.drop_constraint('winners_match_id_fkey', 'winners', type_='foreignkey')
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_winners_user') THEN
                ALTER TABLE winners ADD CONSTRAINT fk_winners_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_winners_match') THEN
                ALTER TABLE winners ADD CONSTRAINT fk_winners_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_losers_user') THEN
                ALTER TABLE losers ADD CONSTRAINT fk_losers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_losers_match') THEN
                ALTER TABLE losers ADD CONSTRAINT fk_losers_match FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('winners_match_id_fkey', 'winners', 'matches', ['match_id'], ['id'])
    op.create_foreign_key('winners_user_id_fkey', 'winners', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_foreign_key('losers_match_id_fkey', 'losers', 'matches', ['match_id'], ['id'])
    op.create_foreign_key('losers_user_id_fkey', 'losers', 'users', ['user_id'], ['id'])
    op.execute("""
        ALTER TABLE winners DROP CONSTRAINT fk_winners_user;
        ALTER TABLE winners DROP CONSTRAINT fk_winners_match;
        ALTER TABLE losers DROP CONSTRAINT fk_losers_user;
        ALTER TABLE losers DROP CONSTRAINT fk_losers_match;
    """)
    # ### end Alembic commands ###

