name: Update Website Status

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check website status
      id: status
      run: |
        status_code=$(curl -o /dev/null -s -w "%{http_code}" https://shuttlestats.com)
        if [ "$status_code" -eq 200 ]; then
          echo "Status: Online" > status.txt
        else
          echo "Status: Offline" > status.txt
        fi
        echo "Last Checked: $(date)" >> status.txt

    - name: Update README.md
      run: |
        # Update the README.md file with the status
        STATUS=$(cat status.txt)
        sed -i "s/.*Last Checked.*/**Last Checked**: $STATUS/" README.md
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update website status"
        git push
